spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/graphql_test?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' to preserve existing data
    show-sql: true  # Enables logging of SQL statements
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
